### PR TITLE
In RF3, components are no longer transformed through … 

### PR DESCRIPTION
**Pull request by frankrolf**
a transformation matrix.

I did not update the collateral, but have the following comments (and can change the files if desired):
– timestamp needs update
– version number needs update
– copyright date in LICENSE file needs to be changed
– a reference to Mechanic2 could be made
– repo name could be changed to reflect this (single) extension.

### CODE REVIEW

**Review by miguelsousa — APPROVED** [review]
@frankrolf go ahead and make the other changes

**Comment by frankrolf** [comment]
Done.
I suggest changing the name of the repo to `adjust-anchors-rf-ext`, aligning with the `kernalytics-rf-ext` extension (and already changed the Mechanic key in info.plist to that destination).

**Comment by frankrolf** [comment]
Once the repo-renaming is done, I’ll change this file here too: 
https://github.com/robofont-mechanic/mechanic-2-server/blob/gh-pages/_data/adjustAnchors.yml

**Comment by miguelsousa** [comment]
Renaming done.

**Comment by frankrolf** [comment]
Thanks! Same on the Mechanic side.

**Pull request merged**
